CORE_CreateMacroVar NGS_EXPLAIN_EXPLANATION_ATTRIBUTE "ngs*explain*explanation"

CORE_CreateMacroVar NGS_EXPLAIN_TAG_SHOULD_EXPLAIN "ngs*explain*should-explain"

CORE_CreateMacroVar NGS_EXPLAIN_AGENT_ID_ATTRIBUTE "agent-id"
CORE_CreateMacroVar NGS_EXPLAIN_CONTEXT_VARIABLES_ATTRIBUTE "context-variables"
CORE_CreateMacroVar NGS_EXPLAIN_GOAL_HIERARCHY_ATTRIBUTE "current-goal-hierarchy"
CORE_CreateMacroVar NGS_EXPLAIN_TASK_AWARENESS_ATTRIBUTE "task-awareness"
CORE_CreateMacroVar NGS_EXPLAIN_INTERNAL_OPERATING_PICTURE_ATTRIBUTE "internal-operating-picture"
